### ISSUE TITLE
DependabotのPRをグループにする

### ISSUE THREAD

**Issue by maehata-fairy** [FairyDevicesRD/thinklet.app.proximity-checker#15]
現在の設定ですと、

![Image](https://github.com/user-attachments/assets/657f8def-c710-40b1-888f-a93c6ee64f45)

のようにライブラリごとにPRが作成されてしまいます。
こうなると、`open-pull-requests-limit: 5` にすぐに抵触してしまいます。

提案：

```
    groups:
      dependencies:
        patterns:
          - "*"
```

のような設定を追加することを推奨します。これにより、複数のライブラリが更新対象であっても１つのPRにまとめてくれるようになります。
